import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Thynksafe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Ensure this runs before React hydration */}
        <Script id="theme-init" strategy="beforeInteractive">
          {`(function(){try{var theme=localStorage.getItem('theme');if(theme==='dark'||theme==='light'){document.documentElement.setAttribute('data-theme',theme);console.debug('[theme-init] loaded from localStorage', theme);return;}var prefersDark=window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.setAttribute('data-theme',prefersDark?'dark':'light');console.debug('[theme-init] using system preference', prefersDark?'dark':'light');}catch(e){console.error('[theme-init] error', e);} })()`}
        </Script>
        {children}
       
      </body>
    </html>
  );
}
